services:
  db:
    image: postgres:12
    ports:
      - "5436:5432"
    env_file:
      - business_trip/.env
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD", "psql", "-U", "postgres", "-c", "SELECT 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    command: [ "postgres", "-c", "log_statement=all", "-c", "wal_level=logical" ]

volumes:
  postgres_data: {}
