project:
  name: Golang Template
  version: 0.0.1

logger:
  level: debug # available debug | info  | error |
  format: text

http:
  timeout: 40s
  idle_timeout: 120s
  max_shutdown_time: 45s # Should be greater than timeout
  